### ISSUE TITLE
Tracking Codes

### ISSUE THREAD

**Issue by colleenmcguckin** [colleenmcguckin/UH#13]
- [ ] make sure the tracking number is being added on donate and not on create
- [x] add a modal/popup/prompty thing to tell donors to write the code on their donation boxes and bring them to the site. 
- [x] if they are relying on the receiving site for transportation they should be notified before they donate! to contact the agency and arrange the transportation
- [x] if they are not relying on the receiving site for transportation they should be notified before they donate! to contact and verify availability and ability to accept donation
